
### ######         windows virtual box         ###########3
# windows data record
GET http://192.168.56.101:7777/recv?dataCode=code3&dataDirectory=/root/data2

###
#  install
GET http://192.168.56.101:7777/install?clientID=wangxiyue-1.agent.id&clientIpAddress=192.168.56.101&recvIpAddress=192.168.56.1&recvPort=2121



######### windows agent ##########################################

###
# install
GET http://127.0.0.1:7777/install?clientID=wangxiyue-1.win10.id&clientIpAddress=127.0.0.1&recvIpAddress=127.0.0.1&recvPort=2121


###
# add record
GET http://127.0.0.1:7777/recv?dataCode=code3&dataDirectory=c:/test/input


###########################################docker client
###
# docker : agent recv
GET http://localhost:58888/recv?dataCode=code1&dataDirectory=/opt

###
# docker : agent install param
GET http://localhost:58888/install?clientID=wangxiyue-1.agent.id&clientIpAddress=host.docker.internal&recvIpAddress=host.docker.internal&recvPort=2121

###########################################docker

#server ###################################
###
# window server install
GET http://localhost:8888/agent/install?host=127.0.0.1&user=root&password=root&port=2222&path=/opt

###
# windows server online
GET http://localhost:8888/agent/online

###
# server save agent to db
GET http://localhost:8888/agent/save?host=127.0.0.1&user=root&password=root&port=2222&path=/opt

###
# server add data record
GET http://localhost:8888/collection/add?clientID=ff80808180e72e490180e72eda0c0002&dataCode=code4&dataDirectory=/opt1

###
# server find data record by clientid
GET http://localhost:8888/collection/find?clientID=ff80808180e72e490180e72eda0c0002